Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../", "/srv/website"
  config.vm.network :forwarded_port, guest: 8124, host: 1234
  config.vm.provision :shell,
    :inline => "sudo apt-add-repository -y ppa:brightbox/ruby-ng && sudo apt-get update && sudo apt-get -y install build-essential git ruby2.3 ruby2.3-dev zlib1g-dev && sudo gem install github-pages therubyracer --no-ri --no-rdoc"
  config.ssh.forward_agent = true
end